1
00:00:00,000 --> 00:00:06,500
Yeesha: Vous revenez encore, vous revenez pour en apprendre plus, cous revenez pour un troisième pillier.

2
00:00:07,000 --> 00:00:12,600
Yeesha: C'est un cycle interessant. Un aller et un retour. On donne et on prend.

3
00:00:13,800 --> 00:00:18,700
Yeesha: Vous devez revenir. Car vous avez déchiré en deux l'être même d'un des Humbles.

4
00:00:19,100 --> 00:00:22,600
Yeesha: Vous avez entendu leur souffrance. Ne faiblissez pas.
