1
00:00:00,000 --> 00:00:05,000
Yeesha: You return again. Return to hear more... return for a third pillar.

2
00:00:05,800 --> 00:00:09,600
Yeesha: It's an interesting cycle -- this coming and going. Giving and taking.

3
00:00:11,000 --> 00:00:17,400
Yeesha: Returning is what you must do, for you have torn in half the very being of one of the Least.

4
00:00:18,000 --> 00:00:21,200
Yeesha: You have heard their pain; don't falter.
